<?php $__env->startSection('content'); ?><p>Men's college basketball and football players at top NCAA schools would make an average of $500,000 and $360,000 a year, respectively, if student athletes earned the same revenue shares as their professional counterparts in the NBA and NFL.</p>

<p>The findings were released in a new study on Tuesday by the National Bureau of Economic Research, which stated that starting quarterbacks and wide receivers would earn $2.4million and $1.3million, respectively, if they were compensated under the terms of the NFL's collective bargaining agreement (CBA). Similarly, starting basketball players would have $800,000 average annual salaries under the NBA's CBA.</p>

<p>NCAA athletes are currently prohibited from profiting off their respective sports. The organization intends to allow athletes to earn money off their name, image and likeness (NIL) beginning in 2021, but a framework for that rule change does not exist yet and the NCAA is petitioning congress for help in that matter. The NCAA has no plans to allow schools to pay players directly.</p>

<p>Clemson's Trevor Lawrence is expected to be among the top picks of the 2021 NFL Draft</p>

<p>Former Georgia guard Anthony Edwards will likely be among the top three players chose at the 2020 NBA Draft. Had he been eligible to be paid in college, he should have earned over $800,000, according to a study based on the revenue sharing plan used by the NBA </p>

<p>Most of college sports in the United States is split into the NCAA's three main divisions, with Division I encompassing the largest schools. Within Division I there are 130 colleges that make up the Football Subdivision (FBS), which is the upper tier of college football and, generally speaking, includes the most profitable athletic departments in the country.</p>

<p>The athletic departments for FBS schools earn a collective $8.5billion in annual revenue.</p>

<p>But while football and men's basketball account for 58 percent of revenue, those athletes receive less than 7 percent of that through scholarships and living stipends.</p>

<p>'Intercollegiate amateur athletics in the US largely bars student-athletes from sharing in any of the profits generated by their participation, which creates substantial economic rents for universities,' read an abstract of the study, which was authored by economic professors at Northwestern and the University of Michigan. </p>

<p>Dayton's Obi Toppin could have earned around $800,000 if college players were compensated like their NBA counterparts </p>

<p>'These rents are primarily generated by men's football and men's basketball programs.'</p>

<p>According to the authors, the current NCAA model is inherently biased against poorer and African-American students in favor of their richer, white classmates. </p>

<p>'The player-level analysis reveals that the existing limits on player compensation effectively transfers resources away from students who are more likely to be black and more likely to come from poor neighborhoods towards students who are more likely to be white and come from higher-income neighborhoods,' read the study's conclusion.</p>

<p>The study use financial figures for FBS schools between 2006 and 2019, then applied those to the NBA and NFL CBAs, which pay players about half of those leagues' revenue.</p>

<p>From 2008 until 2019, the authors wrote, the largest five NCAA conferences (known as the 'Power Five') saw revenue grow 260 percent. In fact, going back to 1999, the NCAA has generated more revenue in basketball and football ticket sales has exceeded those of the NFL, NBA, and NHL combined.</p>

<p>'While intercollegiate sports are often described as student activities undertaken by amateurs, the economic reality is that athletic departments have developed into complex commercial enterprises that look far more like professional sports organizations,' the study states.</p>

<p>Starting wideouts, like LSU wide receiver Ja'Marr Chase (pictured) could earn $1.3 million annually if they were compensated under the same payment structure as NFL players </p>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('_layouts.post', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>