<?php $__env->startSection('content'); ?><p>Historic wildfires which ravaged California throughout August and September may cause 3,000 early deaths, according to research from academics at Stanford University.  </p>

<p>This year there have been over 8,100 wildfires that have burned well over 3.7 million acres in California. Since August 15, when California's fire activity elevated, there have been 26 fatalities and over 7,000 structures destroyed. </p>

<p>On Sunday, 17,000 firefighters were still at work, battling 25 wildfires in the state. </p>

<p>Now academics have concluded that the wildfires, from August 1 to September 10, were responsible already for at least 1,200 deaths in California - and may, over the next month, cause a total of 3,000 deaths.</p>

<p>The fires were also to blame for 4,800 ER visits, they calculated. </p>

<p>Los Angeles is seen blanketed by smoke from wildfires on September 23</p>

<p>California saw wildfires break out across the state, particularly in August and September</p>

<p>A firefighter is pictured battling the Glass Fire in Calistoga, California, on September 27</p>

<p>The fatalities were among people 65 and older, most of whom were living with pre-existing medical conditions such as heart disease, diabetes and respiratory ailments.  </p>

<p>'Clean air is much more important than we realize,' said Marshall Burke, an associate professor of earth system science at Stanford who calculated the impacts. </p>

<p>'When you look at it on a population level, you can see very clearly that breathing clean air has huge public health benefits, and breathing dirty air has disastrous consequences.'</p>

<p>Burke described the fatalities as 'hidden deaths'. </p>

<p>He added: 'These are people who were probably already sick but for whom air pollution made them even sicker.' </p>

<p>Scientists have known for decades that soot, technically termed PM2.5, is among the most dangerous types of air pollution.  </p>

<p>PM2.5 is generated by diesel trucks, power plants, fireplaces and other sources. The tiny particles can travel deep into the lungs, even entering the bloodstream, when people breathe them in high concentrations.</p>

<p>In mild levels they cause itchy eyes and sore throats, coughing and a tight feeling in the chest. In more severe instances, they can trigger asthma attacks, heart attacks, strokes or respiratory failure, particularly in the elderly, infants and people with heart and lung problems.</p>

<p>A burning stack of chairs is seen during the Glass Fire in St Helena, California on September 27</p>

<p>A burnt out car is pictured after the Glass Fire tore through St Helena on September 27</p>

<p>A $100 bill burnt in the Glass Fire is pictured on September 27 in Napa County, California</p>

<p>Smoke levels broke all-time records in California, breaking federal health standards in the Bay Area for 19 days.</p>

<p>Air quality was even worse in the Sierra, the Sacramento Valley and parts of Southern California, where it reached 10 to 15 times the federal health standard. </p>

<p>On September 9, smoke turned the skies across Northern California a strange and sinister orange colour. </p>

<p>'Recent wildfire activity has led to a massive increase in PM2.5 above normal levels,' the scientists wrote. </p>

<p>'As anyone who lives in CA or has watched the news knows, air quality has been terrible, and the monitoring data of course bear this out.'</p>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('_layouts.post', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>