<?php $__env->startSection('content'); ?><p>Microsoft has launched a new tool that can identify 'deepfake' videos that were designed to present false information and a quiz to help people spot them.</p>

<p>There were at least 96 'foreign influenced' deep fake campaigns on social media targeting people in 30 countries between 2013 and 2019, according to Microsoft.</p>

<p>Deepfakes, also known as synthetic media, are photos, videos or audio files manipulated using AI to show or say something that isn't real in a realistic way. </p>

<p>To combat campaigns using this manipulated form of media, the tech giant has launched a new 'Video Authenticator' tool that can analyse a still photo or a video and give the likelihood the media source has been changed.</p>

<p>It works by detecting the blending boundary of the deepfake and subtle fading or greyscale elements that might not be detectable by the human eye.</p>

<p>Microsoft says its Video Authenticator tool looks for signs of blending around the eyes and can give a 'score' showing how likely it is the video has been manipulated</p>

<p>Deepfake campaigns, carried out on social media, sought to defame notable people, persuade the public or polarise debates during elections or a major crisis. </p>

<p>To combat this Microsoft have also launched an online quiz that is designed to 'improve digital literacy' by teaching people about and how to spot a deepfake.</p>

<p>You can try the online quiz on the SpotTheDeepFake.org website. </p>

<p>Some 93 per cent of deepfake campaigns included new original content, 86 per cent amplified pre-existing content and 74 per cent distorted verifiable facts.  </p>

<p>A faked video could appear to make people say things they didn’t or to be places they weren’t - which could harm reputations or even change elections. </p>

<p>Researchers have been creating their own deepfake videos to demonstrate the scale of the technological threat - including MIT producing a video that appears to show Richard Nixon telling the world Apollo 11 ended in disaster.</p>

<p>During the last UK general election, deepfake videos were made of both Boris Johnson and Jeremy Corbyn endorsing each other.</p>

<p>The fact that they’re generated by AI that can continue to learn makes it inevitable that they will beat conventional detection technology, said Microsoft. </p>

<p>However, in the short run, such as the upcoming US election, advanced detection technologies can be a useful tool to help discerning users identify deepfakes. </p>

<p>Microsoft says its new  Authenticator can analyze a still photo or video to provide a percentage chance, or confidence score, that the media is artificially manipulated. </p>

<p>In the case of a video, it can provide this percentage in real-time on each frame as the video plays.   </p>

<p>Video Authenticator was created using a public dataset from Face Forensic++ and was tested on the DeepFake Detection Challenge Dataset, both leading models for training and testing deepfake detection technologies.</p>

<p>We expect that methods for generating synthetic media will continue to grow in sophistication, the tech giant explained. </p>

<p>As all AI detection methods have rates of failure, we have to understand and be ready to respond to deepfakes that slip through detection methods. </p>

<p>Politicians are a major target for deepfake videos - during the last UK general election videos were released that seemed to show Boris Johnson and Jeremy Corbyn supporting one another</p>

<p>'Thus, in the longer term, we must seek stronger methods for maintaining and certifying the authenticity of news articles and other media,' the firm said.</p>

<p>'There are few tools today to help assure readers that the media they’re seeing online came from a trusted source and that it wasn’t altered.'</p>

<p>Microsoft has also launched another new technology that can detect manipulated content and assure people whether it is real or not. </p>

<p>Content producers will be able to add a certificate to say the content is real that travels with it wherever it goes online and and a browser extension will be able to read the certificate and tell people if it is the authentic version of a video.  </p>

<p>To improve digital literacy Microsoft launched a tool that aims to train people to be better at spotting deeepfake images and videos</p>

<p>Even with new technology to 'catch and warn' people about deepfakes, that won't stop everyone being fooled or every deepfake from getting through.</p>

<p>Microsoft has also worked with the University of Washington to improve media literacy to help people sort disinformation from genuine facts.</p>

<p>'Practical media knowledge can enable us all to think critically about the context of media and become more engaged citizens while still appreciating satire and parody,' the firm wrote in a blog post. </p>

<p>'Though not all synthetic media is bad, even a short intervention with media literacy resources has been shown to help people identify it and treat it more cautiously.'</p>

<p>They have launched an interactive quiz for voters in the upcoming US election to help them learn about synthetic media, develop critical media literacy skills and get a deeper understanding of the impact deepfakes can have on democracy.</p>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('_layouts.post', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>