<?php $__env->startSection('content'); ?><p>Opening an air corridor between London and New York, together with testing and tracing at the UK's airports, is a necessity if Britain is to thrive again. </p>

<p>Not only is the estimated £52billion of national income generated by aviation at stake, but also Britain's role as an entrepot economy and an aerospace champion. </p>

<p>The eye-popping first-half loss of £5.4billion at Rolls-Royce should be a wake-up call on Downing Street and in Whitehall. </p>

<p>Up in the air: Opening an air corridor between London and New York is a necessity if Britain is to thrive again</p>

<p>Much of the loss can be explained by accounting, but when wide-bodied aircraft around the world are grounded, income for Rolls-Royce and its suppliers is badly compromised and Britain's industrial heartland at risk. When France unveiled its £13.4billion bail-out package for aviation in June it recognised the supply chain. There was cash for Air France, but also for Airbus and aerospace suppliers. </p>

<p>Rolls-Royce's chief executive Warren East is determined to navigate the aircraft engine maker out of the Covid turbulence without direct government intervention. </p>

<p>The chief executive demands a fair wind in the shape of a reopening of the Atlantic routes, which he describes as an 'excellent idea', R&amp;D support for Rolls-Royce work on next generation engines and defence spending – in particular for the Tempest fighter.</p>

<p>East gives no grounds to those arguing that Rolls-Royce is facing an existential crisis as when it was nationalised by the Heath government in 1971. But deep into its interim statement there is a warning that a further downturn could jeopardise its ability to trade as a going concern. Rolls is shrinking operations, focusing on sites in Derby, and jettisoning marginal enterprises, including Spanish based ITP Aero, to strengthen capital by £2billion. It is also looking to tap shareholders for a similar amount, weakening a savaged share price. </p>

<p>East's effort to pull Rolls out of its nosedive is not helped by the decision of finance director Stephen Daintith to hit the ejector seat in the midst of pandemic. The opportunity to join the rich kids at Ocado may have been overwhelming, but departing from an totemic company mid-crisis is, as East observed, 'clumsy', even if he did a good job in paying down debt in his three-year sojourn. </p>

<p>Strip losses down to the core and the results don't look so bad. Unwinding dollar hedges, stretching way into the future, cost £1.5billion and write-offs and other accounting clean-ups, as the company reshapes, came to another £1.5billion or so. Nevertheless, free cash flow plummeted with £2.8billion fleeing in the first half. East is promising positive territory next year. That will depend on a big recovery in flying hours. As much as the noise pains me, it would be good to see the big birds descending over Richmond Park again.</p>

<p>Body building </p>

<p>The Hut Group's supercool founder Matthew Moulding deserves credit for choosing to float in London. Too many European tech groups have chosen the bright lights of Nasdaq in Time Square over the calmer environs of Paternoster in the shadow of St Paul's. The Hut is following the same route as Ocado, which is now more valuable than all the other grocers added together with the exception of Tesco. </p>

<p>Hut's two main offshoots, Myprotein and Lookfantastic, are in the fashionable beauty, lifestyle market, although claims of Myprotein to be the world's number one sports nutrition brand might be worth scrutiny. </p>

<p>The desperation of City-based firms to be part of a rare multi-billion FTSE initial public offering is evident from the IPO document, which reads like a Who's Who of world bankers and brokers with Rothschild described as 'financial adviser'. Pardon the error, but I thought they all were from JP Morgan Cazenove through to Goldman. </p>

<p>Given the distinguished cast, it is a pity more attention wasn't paid to governance. The concept of Moulding as executive chairman and chief executive doesn't scream City code. Wealthy senior non-executive Zillah Byng-Thorne is a former adviser to the company (so not that independent). Iain McDonald as chair of the pay committee at Boohoo has presided over one of the most outrageous bonus deals in the UK. </p>

<p>Doesn't look that robust.</p>

<p>Strike force </p>

<p>The idea of shopping warehouse giant Walmart teaming up with Microsoft to buy the US bit of TikTok, which has just parted ways with chief executive Kevin Mayer, looks weird. Amazon must really be scaring them at HQ in Bentonville, Arkansas. </p>

<p>Send for the cold compress.  </p>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('_layouts.post', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>