<?php $__env->startSection('content'); ?><p>Shoes that curve up at the toe – known as toe springs – require less muscle work, but they can weaken foot muscles in the long term, biomechanics experts claim. </p>

<p>Toe springs, which are a common feature of athletic shoes, keep toes continually elevated above the ground to help the front part of the foot roll forward during motion. </p>

<p>US and German researchers analysed the effects of different shoes with toe springs at various angles using infrared cameras and 3D motion data. </p>

<p>The more curved a toe spring is, the less power the foot has to exert when pushing off from the ground while walking or running, they found.</p>

<p>Toe springs can therefore weaken muscles in the feet and shift much of the muscle work to a long web-like ligament connecting the heal bone to the toes in the bottom of the foot – called the plantar fascia.</p>

<p>This can cause plantar fasciitis – a condition that leads to intense pain at the heel, hindering even the slightest of movement. </p>

<p>Toe springs keep the toes continually elevated above the ground in a flexed upwards position to help the front part of the foot roll forward when walking or running. Image of the foot in a shoe with high toe spring angle, with the plantar fascia in red</p>

<p>'It stands to reason that if the foot muscles have to do less work, then they're probably going to have less endurance given that many thousands of times a day you push off on your toes,' said Harvard University paleoanthropologist Dr Daniel Lieberman, senior study author.  </p>

<p>'One of the biggest problems in the world today of people's feet is plantar fasciitis. </p>

<p>'We think that what happens is that people are relying on their plantar fascia to do what muscles normally do. </p>

<p>'When you get weak muscles and the plantar fascia has to do more work, it's not really evolved for that, and so it gets inflamed.' </p>

<p>Shoe manufacturers may be responsible for inflicting long-term foot problems, although runners may still think toe springs are worth it.  </p>

<p>'We like comfort – that's why we sit in chairs and take elevators,' Dr Lieberman said. </p>

<p>Plantar fasciitis is one of the most common causes of heel pain, affecting the long web-like ligament connecting the heal bone to the toes in the bottom of the foot – the plantar fascia</p>

<p>Graphic of a toe spring, which tend to be of a more modest angle in everyday shoes but are accentuated for sportswear designs </p>

<p>The researchers investigated the effects of toe springs on foot biomechanics on 13 participants, who were all made to walk barefoot on a treadmill at a comfortable pace. </p>

<p>The treadmill was equipped with force plates and an infrared camera system to measure how much power was put into each step. </p>

<p>The participants were then asked to repeat the process wearing four different pairs of specially designed sandals with varying upward curvature of the toe region, ranging from 10 degrees to 40 degrees. </p>

<p>The special footwear was designed to mimic the stiffness and shape found in commercially available shoes. </p>

<p>3D motion data were captured using markers placed on each subject's knee, ankle and foot.</p>

<p>The higher the upwards curve of the toes in respect to the rest of the foot, the less work the foot muscles had to perform to support the joints when walking, they found.  </p>

<p>The propulsive force generated by the 'metatarsophalangeal' or MTP joints – where the toes connect to the rest of the foot bones – decreased as the curve of the toe spring on the sandals increased, they found. </p>

<p>The plantar fascia wraps around the bony MTP joints and stretches all the way back to the heel. </p>

<p>Custom-made sandals with varying degrees of toe spring angle were manufactured to mimic the stifness and shape of toe springs commonly found in commercially available shoes</p>

<p>Image showing propulsive force generated by the metatarsophalangeal or MTP joints and ground reaction force (vGRF)  </p>

<p>MTP joints are one of the key features that have evolved so that humans can walk and run on two feet so effectively. </p>

<p>Toe springs may be a comfortable feature of modern trainers and help sportspeople kick off, but they could contribute to weakening of toe muscle with long-term use. </p>

<p>'Intrinsic foot muscles play an important role in helping to stiffen the MTP joints as they are being dorsifexed [bent backwards] at the end of a step in walking and running,' the researchers say in their paper.</p>

<p>'By reducing moments at the MTP joints, toe springs likely relieve the intrinsic foot muscles of some of the work necessary to stiffen these joints.</p>

<p>'These small differences in muscle work likely add up to substantial differences over time when considering that the average individual in industrialized countries takes 4,000 to 6,000 steps per day. </p>

<p>'Thus, habitually wearing shoes with toe springs could inhibit or de-condition the force generating capacity of intrinsic foot muscles.'   </p>

<p>Toe springs may contribute to weakening of the foot muscles and possibly to increased susceptibility to common pathological conditions such as plantar fasciitis</p>

<p>The researchers admitted their study does not directly link toe springs with plantar fasciitis or other common foot problems – meaning more research is needed. </p>

<p>The study also included only habitual shoe users whose feet may already have been adapted to shoes with toe springs, meaning the results could be different with participants who only wear flat shoes. </p>

<p>Future research will investigate how toe springs interact with other elements of shoes, such as stiff soles or cushioning.   </p>

<p>'From an evolutionary perspective, wearing modern shoes that have arch supports, cushioning, and other supportive features is a very recent phenomenon,' said study author Freddy Sichting at Chemnitz University of Technology in Germany.</p>

<p>'Several lines of evidence suggest that weak foot muscles may be partly a consequence of such features.' </p>

<p>The study has been published in Scientific Reports.    </p>

<p>Plantar fasciitis is one of the most common causes of heel pain.</p>

<p>It involves inflammation of a thick band of tissue that runs across the bottom of the foot and connects the heel bone to your toes (plantar fascia).</p>

<p>Plantar fasciitis commonly causes stabbing pain that usually occurs with the first steps of the day. </p>

<p>As we get up and move, the pain normally decreases, but it might return after long periods of standing or when we stand up after sitting.</p>

<p>Plantar fasciitis is more common in runners. </p>

<p>People who are overweight and those who wear shoes with inadequate support also have an increased risk of plantar fasciitis.</p>

<p>Plantar fasciitis typically causes a stabbing pain in the bottom of your foot near the heel.  </p>

<p>The pain is usually worse after exercise, not during.</p>

<p>The plantar fascia is in the shape of a bowstring, supporting the arch of the foot and absorbing shock when walking. </p>

<p>If tension and stress on this bowstring become too great, small tears can occur in the fascia. </p>

<p>Repeated stretching and tearing can irritate or inflame the fascia, although the cause remains unclear in many cases of plantar fasciitis. </p>

<p>Source: Mayo Clinic  </p>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('_layouts.post', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>