<?php $__env->startSection('content'); ?><p>Furious demonstrators blocked one of Scott Morrison's security cars and shouted obscenities in a heated climate change protest on Thursday.</p>

<p>Four women waving flags walked in front of the car as it left Blue Scope Steel in Port Kembla, New South Wales, where the prime minister had just announced new investment in renewable energy. </p>

<p>Climate change activists have been angered by Mr Morrison's threat this week to build a new gas-fired power station to replace a coal plant which is shutting down in 2023.</p>

<p>Furious demonstrators blocked one of Scott Morrison's security cars and shouted obscenities in a heated climate change protest on Thursday</p>

<p>'Scott Morrison wants to come here and say he wants to destroy people's lives,' the woman leading the protest shouted.</p>

<p>Referencing last year's shocking bushfire season, she said: 'He wants the entire f****** country to burn again this summer.</p>

<p>'He doesn't give a f*** about anyone else but himself or the pockets of big business.' </p>

<p>On Tuesday Mr Morrison backed the coal industry, saying: 'Coal will continue to play an important part of our economy for decades to come.' </p>

<p>The woman yelled: 'He cares about digging coal out of the ground, he doesn't care about solar energy, he doesn't care about his children's future.'</p>

<p>The security detail in the car, which did not contain Mr Morrison, waited patiently until the women moved on. </p>

<p>The centerpiece of Mr Morrison's plan is to build a giant hydrogen export hub worth $70million where the gas can be shipped to countries around the world. Pictured: The Pilbara port in WA</p>

<p>Carbon capture: $50million</p>

<p>Microgrids: $67million</p>

<p>New air-con: $52million</p>

<p>Hydrogen hub: $70million</p>

<p>Funding for Australian Renewable Energy Agency: $1.4billion </p>

<p>On Tuesday Mr Morrison said he stands ready to build a new gas-fired power station in the New South Wales Hunter Valley to keep power prices down as Australia emerges from the coronavirus-caused recession.</p>

<p>The prime minister wants to reform the gas market to stop Aussies getting ripped off while major producers send $49billion of gas a year overseas, mainly to Japan, China and South Korea.</p>

<p>He will require energy companies in New South Wales to make plans to produce 1000MW of power by April 2021 - and if they don't he will step in and build a new gas-fired power station at Kurri Kurri.</p>

<p>A new plant there would replace power generated by the Liddell Coal plant which is due to close in 2023.  </p>

<p>At the same time, Mr Morrison will also invest in new technology to reduce emissions over the next ten years.</p>

<p>Some $1.9billion will be spent on  measures including solar-powered microgrids for farmers, a new $70million hydrogen export hub and more energy-efficient air-conditioning systems for regional pubs.</p>

<p>The centerpiece of Mr Morrison's plan is to build a giant hydrogen export hub worth $70million where the gas can be shipped to countries around the world including Japan, South Korea, Singapore and Germany. </p>

<p>Some $30billion has been invested in renewable energy in Australia since 2017, with dozens of solar power and wind farms popping up around the country. </p>

<p>A new gas plant in the Hunter Valley would replace power generated by the Liddell Coal plant (pictured) which is due to close in 2023</p>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('_layouts.post', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>