<?php $__env->startSection('content'); ?><p>Victoria Beckham and Simon Cowell are the highest-ranking Britons in a global league table cataloguing the money generated by celebrity businesses.</p>

<p>The fashion designer, 46, and music mogul, 60, are joint 12th in the table, each earning an estimated £34million in annual revenue from their companies, according to analysis.</p>

<p>It looked at the businesses launched by celebrities rather than how much they earn directly from their fame in the entertainment industry. </p>

<p>Raking it in: Victoria Beckham (L) and Simon Cowell (R) are the highest-ranking Britons in a global league table cataloguing the money generated by celebrity businesses </p>

<p>Mrs Beckham, who is married to former England football captain David, runs a clothing label that carries her name.</p>

<p>In May, the former Spice Girl axed plans to furlough around 30 of the company’s 120 staff after facing criticism for drawing on the public purse. Later in the summer, she was forced to let 20 staff go to ‘future proof’ her company.</p>

<p>Meanwhile, Cowell, who is recovering from a broken back after falling off an electric bike, owns entertainment company Syco – a record label and talent agency which also produces TV and film.</p>

<p>The research, published by marketing firm Digitaloft and online betting analysts OLBG, ranked American rapper Dr.Dre, 55, at number one.</p>

<p>Kerching! Singer Rihanna took third place with her Fenty collection of fashion and beauty companies, netting the Barbadian singer a combined total of around £860million a year</p>

<p>£1.2billion-a-year: Research by marketing firm Digitaloft and online betting analysts OLBG, ranked American rapper Dr.Dre at number one for his company Beats Electronics</p>

<p>Fashion savvy: Mrs Beckham, who is married to former England football captain David (pictured), runs a clothing label that carries her name</p>

<p>Empire: Businessman Simon, who is recovering from a broken back, owns entertainment company Syco (pictured with partner Lauren Silverman)</p>

<p>His headphone and speaker company Beats Electronics, founded as Beats by Dr. Dre in 2006, earns him an estimated £1.2billion a year.</p>

<p>He is followed by Kanye West, 43, in second, who earns around £1billion annually from his Yeezy trainers and clothing line – a collaboration with sportswear brand Adidas.</p>

<p>His wife Kim Kardashian, 39, is also in the top ten, with her beauty range netting her £77million a year.</p>

<p>Power couple: In second is Kanye West who earns around £1billion annually from his Yeezy line, while his wife Kim Kardashian takes home £77million a year from her beauty range</p>

<p>Rihanna, 32, took third place with her Fenty collection of fashion and beauty companies. They netted the Barbadian singer a combined total of around £860million a year.</p>

<p>Several actresses featured prominently in the top ten.</p>

<p>Jessica Alba, 39, earns around £295million a year from the Honest Company, which makes natural baby products.</p>

<p>Juggling act: Jessica Alba earns around £295million a year from the Honest Company, which makes natural baby products</p>

<p>On top: The actresses were trumped by Jessica Simpson, who rose to fame as a singer and now makes £770 million a year from her eponymous fashion brand</p>

<p>Kate Hudson, 41, gets £232million from Fabletics sportswear and child star twins Mary-Kate and Ashley Olsen, both 34, get around £114million from fashion brand The Row.</p>

<p>But the actresses were trumped by Jessica Simpson, 40, who rose to fame as a singer and now makes £770 million a year from her eponymous fashion brand.</p>

<p>Irish musician Bono took 30th position. The 60-year-old U2 frontman co-founded successful private equity firm Elevation Partners in 2004, which now earns him over £12million a year.</p>

<p>Working hard: Irish musician Bono took 30th position as his successful private equity firm Elevation Partners earns him over £12million a year</p>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('_layouts.post', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>