<?php $__env->startSection('content'); ?><p>Britain's Got Talent has reportedly received complaints to Ofcom over a lack of social distancing during Saturday's show.</p>

<p>Judges Amanda Holden, Alesha Dixon, David Walliams and Ashley Banjo took part in magician Kevin Quantum's trick with Ant McPartlin and Declan Donnelly.</p>

<p>The trickster wanted the stars to help him break a glass with an electrical current which would be generated by human contact through a plasma globe, but the magic act required them to touch fingers.</p>

<p>Touching; Britain's Got Talent has been hit by MORE Ofcom complaints as viewers 'criticise show for a lack of social distancing during magic trick', it was reported on Tuesday</p>

<p>Prior to the trick, Kevin did ask all of the judges to sanitise their hands and made sure they stood at a two metre distance before they touched hands.</p>

<p>Despite doing this, some fans felt that it was against social distancing measures to allow the judges and co-hosts to touch hands, and took to Twitter to complain.</p>

<p>One user said: 'A bit hypocritical to have the judges sitting 2 metres apart and then get them on the stage touching each other. Hope they all washed their hands after.'</p>

<p>Act: Magician Kevin Quantum wanted the stars to help him break a glass with an electrical current which would be generated by human contact through a plasma globe</p>

<p>Staying safe: Prior to the trick, Kevin did ask all of the judges to sanitise their hands and made sure they stood at a two metre distance before they touched hands.</p>

<p>While another criticised: '#BGT so no social distancing on the show tonight, touching each other's fingers?'</p>

<p>Another viewer questioned: 'Surely they can't be touching each other?' </p>

<p>The Sun reported on Tuesday that the regulatory board had received 19 complaints regarding the magic act.  </p>

<p>Britain's Got Talent producers told Metro on Saturday: 'We operate to comprehensive Covid-19 policies and film in compliance with the law including ensuring personal contact on stage is for the shortest time; hands are sanitised; equipment is disinfected; participants are not face to face and the studio is well ventilated. </p>

<p>Unhappy: Despite doing this, some fans felt that it was against social distancing measures to allow the judges and co-hosts to touch hands, and took to Twitter to complain</p>

<p>'For Kevin's performance, hand sanitiser was used by him, the judges and Ant; props were disinfected; and any close contact was kept to a minimum.' </p>

<p>MailOnline has contacted Ofcom and Britain's Got Talent representatives for further comment.</p>

<p>On Monday it was claimed Amanda had sparked Ofcom complaints once more from viewers, with 235 people contacting the company over her outfit from Saturday's show. </p>

<p>The Heart Breakfast presenter wowed in a showstopping metallic navy gown during the fourth semi-final, but at the time some fans questioned if she had suffered a wardrobe malfunction after they claimed to 'see her nipples'.</p>

<p>Risque: On Monday, it was claimed Amanda had sparked Ofcom complaints once more from viewers, with 235 people contacting the company over her outfit</p>

<p>Racy: The Heart Breakfast presenter wowed in a showstopping metallic navy gown during the fourth semi-final, but some fans claimed they could 'see her nipples'</p>

<p>According to a report from The Mirror, the regulator received 277 complaints about the programme, with the majority focusing on her racy ensemble which featured a plunging neckline and was boned to accentuate her cleavage. </p>

<p>The broadcaster told her Instagram followers on Tuesday: 'Mmmm really?! Who has nipples this close to their cleavage?! </p>

<p>'FYI. A boned corset dented the girls all night', she ended her post alongside a series of fried egg emojis. </p>

<p>Meanwhile Diversity's Black Lives Matter inspired performance during the show's first semi-final attracted 24,500 complaints to OfCom, who have since announced they will not investigate any further.</p>

<p>Controversy: Meanwhile, Diversity's dance earlier this month sparked 24,500 complaints but  Ofcom have since announced they will not investigate any further</p>

<p>ITV has 'stood with Diversity' as they featured adverts in national newspapers in support of the controversial dance. </p>

<p>ITV are believed to have spent around £260,000 on the newspaper ads with full-page monochrome pieces in The Metro costing £36,461 and £27,700 in The Mirror. </p>

<p>Alesha was one of many who praised ITV for standing by the dance troupe. The singer took to Instagram to share a snap of the advert and gushed over how 'proud' she was with them. </p>

<p>In her caption, she wrote: 'Well done <?php echo e('@'); ?>ITV for standing with Diversity! Proud of you! This image is in all of the national newspapers today.'</p>

<p>Making a statement: ITV rolled out full-page ads in solidarity with Diversity as Ofcom complaints reach 24,500 over the groups BLM-inspired routine. Ashley pictured</p>

<p>Decision: A spokesperson for government-approved regulatory body Ofcom confirmed to MailOnline no action will be taken for Diversity's BLM-inspired routine </p>

<p>Ashley also shared his gratitude with ITV for standing by Diversity over their Black Lives Matter-inspired performance. </p>

<p>The poster showed a poignant black and white image of Ashley taking the knee alongside the words: 'We are changed by what we see. Just as we are changed when we are seen. ITV stand with Diversity.'</p>

<p>Sharing a snap of the same advert, which shows him kneeling in black-and-white, he wrote: 'This is what change looks like.</p>

<p>'<?php echo e('@'); ?>ITV stand with <?php echo e('@'); ?>Diversity and we've never been prouder. This is in all the national papers today. Thank you again to everyone that has supported us.'</p>

<p>Support: The broadcaster shared a statement on their Twitter page as the furore continued</p>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('_layouts.post', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>