<?php $__env->startSection('content'); ?><p>Talking loudly in pubs is just as risky as singing when it comes to spreading Covid-19, a UK Government-backed study has found.</p>

<p>The research was used to inform ministers' decision to allow indoor concerts and stage performances to resume last week. It comes as a major boost for the arts and entertainment industry, which has been obliterated financially by the pandemic. </p>

<p>But questions will be raised about people's safety in rowdy pubs, where there is often music playing and revellers have to shout to be heard.</p>

<p>Previous studies had indicated that prolonged singing produced more aerosols and therefore made it easier for Covid-19 to infect people.</p>

<p>The virus is mainly released into the atmosphere when the infected produce plumes of droplets, often through coughing or sneezing. </p>

<p>Smaller infectious particles called aerosols are released by talking loudly. These can linger in the air for longer periods of time and can be inhaled. </p>

<p>The latest paper, carried out by a team of British scientists and supported by Public Health England and the Department for Digital, Culture, Media and Sport, concluded that singing produced just as much aerosols as speaking loudly.</p>

<p>Singing is no more risky than talking loudly when it comes to spreading coronavirus, a UK Government-backed study has found (file) </p>

<p>Questions will be raised about people's safety in rowdy pubs, where there is often music playing and revellers have to shout to be heard</p>

<p>The academics, from Imperial College London, University of Bristol, Wexham Park Hospital, Lewisham and Greenwich NHS Trust and the Royal Brompton Hospital, examined the amount of aerosols and droplets generated by 25 professional singers.</p>

<p>The performers were asked to do singing, speaking and breathing exercises and were also examined while coughing. </p>

<p>The Government's Scientific Advisory Group for Emergencies (Sage) earmarked live musical performances and choirs were one of the more risky events for Covid.</p>

<p>This was why music venues, indoor theatres and concerts were the very last amenities to reopen following lockdown.</p>

<p>In a report submitted sometime in June, SAGE said it had reviewed a number of international studies and found evidence to suggest that singing can produce more aerosols, or droplet nuclei, than normal talking or breathing.</p>

<p>Covid-19 is spread through respiratory secretions, which can take the form of large droplets or smaller aerosols.</p>

<p>These are either inhaled directly or transferred by the hands from surfaces where they have been deposited.</p>

<p>The document says that the smaller the particle, the further it can advance into the respiratory tract.</p>

<p>The authors said: 'There exists some evidence to suggest that singing can produce more aerosols than normal talking or breathing; it may be more akin to a cough.</p>

<p>'Singing for any appreciable amount of time therefore may present a risk for the creation of infectious aerosols and allow for infection transmission.' </p>

<p>The authors added: ''Therefore, at the present time the safest way for groups to sing together is to i) sing outside, ii) use the 2m rule to socially distance and iii) avoid face-to-face positioning.'</p>

<p>Exercises included individuals singing and speaking 'Happy Birthday' at various noise levels.</p>

<p>The researchers found that the aerosol mass produced rose steeply with an increase in volume of singing or speaking, by as much as 20 to 30 times.</p>

<p>But singing did not produce substantially more aerosols than speaking at a similar volume.</p>

<p>There was also no difference in aerosol production between different genres such as choral, musical theatre, opera, jazz, gospel rock or pop.</p>

<p>Professor Jonathan Reid, who lead the study, said: 'The study has shown the transmission of viruses in small aerosol particles generated when someone sings or speaks are equally possible with both activities generating similar numbers of particles.</p>

<p>'Our research has provided a rigorous scientific basis for Covid-19 recommendations for arts venues to operate safely for both the performers and audience by ensuring that spaces are appropriately ventilated to reduce the risk of airborne transmission.'</p>

<p>Dr Julian Tang, honorary associate professor in respiratory sciences at the University of Leicester, described it as a 'useful study' but poked holes in its methodology.</p>

<p>She pointed out that the researchers only analysed singers on a one-to-one basis, whereas live musical performances normally see multiple people singing at once.</p>

<p>She said: 'This is a useful and timely study... showing that singing produces a similar particle size/number distribution as talking. </p>

<p>'But it is indeed the volume of singing – especially in large groups – that is important with more particles produced as the singing gets louder – and this is the point.</p>

<p>'But the risks should not be overly underestimated or played down because of this – we don't want choir members getting infected and potentially dying from COVID-19 whilst doing what they love.</p>

<p>'Also, the study was performed on individual singers one at a time – when the particle profile was found to be similar to talking. </p>

<p>Again, this is not necessarily the main problem. The risk is amplified when a group of singers are singing together, e.g. singing to an audience, whether in churches or concert halls or theatres. </p>

<p>'So it is a nice study but not exactly representative of the real whole choir dynamic which really needs further study to truly assess the risk of such large volume synchronised singing vocalisations/exhalations.' </p>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('_layouts.post', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>