<?php $__env->startSection('content'); ?><p>Large multinational companies and their wide-reaching supply chains are to blame for almost one fifth of the world's carbon dioxide emissions. </p>

<p>A study found the true carbon footprint of companies such as Total and BP is concealed due to how emissions are reported. </p>

<p>Scientists from the UK and China mapped emissions generated by multinationals' assets and their suppliers abroad.  </p>

<p>Carbon emissions from multinationals' foreign investment were 18.7 per cent of all emissions in 2016, they found. </p>

<p>Despite falling slightly from a peak of 22 per cent in 2011, huge companies in the US continue to invest in developing countries, meaning emissions are 'outsourced' to poorer parts of the world.   </p>

<p>Carbon dioxide produced by the foreign affiliates of BP and Total exceeds the oil industry emissions from the supply chains of big companies located in every country in the world, except the gas-guzzling US.  </p>

<p>The study found Samsung and Apple generated more emissions abroad than the whole of the foreign-owned electronics sectors for multiple Asian countries.</p>

<p>Scroll down for video </p>

<p>Pictured, a graph showing the amount of Co2 in megatonnes produced by the petroleum sector in 2016. The blue bars represent the carbon emissions in supply chains of MNEs in a certain country. The dotted vertical  lines represent the carbon emissions in supply chains of large foreign affiliates of Total SA and BP</p>

<p>The UK's BP generated more emissions through its foreign affiliates than the foreign-owned oil industry in any country, except for the US</p>

<p>Foreign direct investment (FDI) is a category of cross-border investment.</p>

<p>It's a business in one country controlling ownership of a  business in another country.    </p>

<p>FDI is an important channel for the transfer of technology between countries, promotes international trade through access to foreign markets, and can be an important vehicle for economic development.  </p>

<p>However, it can lead to stifling of domestic competition and entrepreneurship and interference by foreign governments. </p>

<p>The researchers argue that emissions should therefore be assigned to countries where the investment comes from, rather than countries where the emissions are generated. </p>

<p>'Multinational companies have enormous influence stretching far beyond national borders,' said study author Professor Dabo Guan at University College London. </p>

<p>'If the world's leading companies exercised leadership on climate change – for instance, by requiring energy efficiency in their supply chains – they could have a transformative effect on global efforts to reduce emissions.</p>

<p>'However, companies' climate change policies often have little effect when it comes to big investment decisions such as where to build supply chains.</p>

<p>'Assigning emissions to the investor country means multinationals are more accountable for the emissions they generate as a result of these decisions.' </p>

<p>Multinational enterprises (MNEs) engage in foreign direct investment, allowing them substantial influence over the entire supply chain. </p>

<p>A country can reduce its territorial emissions by importing products from other countries through international trade. </p>

<p>Global carbon transfer for the years 2011 (top) and 2016 (bottom). The colour of each country or region represents the gross volume of CO2 emissions driven by foreign direct investment (FDI) stocks that are sourced from that country or region. The arrows represent the carbon transfer through global FDI. The width of the arrows represents the volume of carbon flow</p>

<p>Carbon emissions in the supply chains of large foreign affiliates of MNEs, as of 2016, in MtCO2:   </p>

<p>Coca-Cola 33 </p>

<p>PepsiCO.Inc 28 </p>

<p>Total SA 38 </p>

<p>BP 34 </p>

<p>DOW 53 </p>

<p>BASF 44 </p>

<p>Samsung 18 </p>

<p>Apple 11 </p>

<p>Volkswagen 51 </p>

<p>Toyota 31 </p>

<p>Costco 3  </p>

<p>However, a country can outsource carbon emissions to other countries through investment as well.  </p>

<p>For their study, researchers traced the carbon footprints of foreign affiliates of MNEs and examined the emissions that the world's largest companies generated through foreign investment.</p>

<p>It found that oil giant Total SA's foreign affiliates generated more than a tenth of the total emissions of France. </p>

<p>The UK's BP generated more emissions through its foreign affiliates than the foreign-owned oil industry in any country, except for the US.</p>

<p>US retail giant Walmart generated more emissions abroad than the whole of Germany's foreign-owned retail sector, as well as that of the UK, Hong Kong, Russian and France. </p>

<p>While Coca-Cola's emissions around the world were equivalent to the whole of the foreign-owned food and drink industry hosted by China.  </p>

<p>In the electronic manufacturing sector, Samsung was responsible for more emissions than rival Apple.</p>

<p>Samsung generated more emissions abroad than the whole of Vietnam, Taipei, India, Thailand and Singapore's foreign-owned electronics sector. </p>

<p>Mapping the global flow of investment, researchers found steady increases in investment from developed to developing countries. </p>

<p>Carbon footprint of MNEs in the electronics sector in 2016 (MtCO2 at both axes). The blue bars represent the carbon emissions in supply chains of MNEs in a certain country. The lines represent the carbon emissions in supply chains of large foreign affiliates of Samsung and Apple </p>

<p>Between 2011 and 2016 emissions generated through investment from the US to India increased from 48.3 million tons to 70.7 million tons.</p>

<p>And emissions generated through investment from China to south-east Asia increased from 0.7 million tons to 8.2 million tons.  </p>

<p>'Multinationals are increasingly transferring investment from developed to developing countries,' said the study's lead author Dr Zengkai Zhang of Tianjin University. </p>

<p>'This has the effect of reducing developed countries' emissions while placing a greater emissions burden on poorer countries.</p>

<p>'At the same time it is likely to create higher emissions overall, as investment is moved to more carbon-intense regions.'   </p>

<p>The study also revealed the carbon footprints of MNEs overall, which grew from 5,530 metric tonnes of carbon dioxide (MtCO2) in 2005 to a peak of 6,419 MtCO2 in 2008. </p>

<p>After the financial crisis, the carbon footprints of MNEs increased again and reached the highest peak of 6,677 MtCO2 in 2011. </p>

<p>After 2011, there was a general declining pattern in the carbon footprints of MNEs, which was down to 6,543.4 MtCO2 in 2014 and 6,048.9 MtCO2 in 2016.     </p>

<p>Apple launched Apple’s Supplier Clean Energy Program to advance the use of clean energy in its supply chain</p>

<p>The gross volume of global carbon transfer through investment peaked in 2011, mainly driven by the decline in carbon intensity. </p>

<p>Researchers said the fall since 2011 has been a result of 'de-globalisation', with the volume of foreign direct investment shrinking and new technologies and processes making industries more carbon efficient. </p>

<p>MailOnline has contacted BP for comment.  </p>

<p>The study, published in Nature Climate Change, admitted that some MNEs have played active roles in fighting climate change. </p>

<p>For instance, in 2015, Apple, the world’s largest technology company by revenue, launched Apple’s Supplier Clean Energy Program to advance the use of clean energy in its supply chain.  </p>

<p>In July this year, Apple said it will be 100 per cent carbon neutral by 2030 by offsetting emissions of the greenhouse gas from its operations.</p>

<p>The iPhone maker said it will have a net zero carbon footprint in 10 years across its entire business, including its manufacturing supply chain.</p>

<p>Apple is already carbon neutral for its global corporate operations, such as its offices and data centres, which are powered by 100 per cent renewable energy.  </p>

<p>Apple's most recent environmental report, covering the fiscal year 2018, put its carbon footprint at 25.2 million tons. </p>

<p>The company is responsible for consuming huge quantities of energy to sustain its operations, generated from carbon-generating power sources.  </p>

<p>Tech companies such as Apple are feeling the pressure to curb their carbon footprint to avoid potentially catastrophic effects of global warming at the end of this century.   </p>

<p>Plans for the UK to become 'carbon' neutral by 2050 were released by Theresa May's government on June 12, 2019.</p>

<p>However, experts are concerned over how the proposals will work.</p>

<p>The report commits to ensuring that the emissions generated by the UK are offset by removing the same amount of carbon from the atmosphere.</p>

<p>There are two main ways this can be achieved - by planting more trees and by installing 'carbon capture' technology at the source of the pollution.</p>

<p>Some critics are worried that this first option will be used by the government to export it's carbon offsetting to other countries.</p>

<p>International carbon credits let nations continue emitting carbon while paying for trees to be planted elsewhere, balancing out their emissions.</p>

<p>Some argue that the scheme is a way for developed nations to shirk their environmental obligations, by passing them to poor and developing countries.</p>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('_layouts.post', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>