<?php $__env->startSection('content'); ?><p>A feasibility study commissioned by minsters on ways to accelerate the uptake of electric vehicles has suggested making new petrol and diesel cars £1,500 more expensive.</p>

<p>The report, published by the Department for Transport this week, said the funds generated by the additional cost of motors with internal combustion engines could be used to subsidise battery vehicles, which are generally more expensive to buy.</p>

<p>But the motor industry's trade body has blasted the suggestion, saying such a move would penalise those who can't afford electric cars currently, or don't have the facilities to charge them.</p>

<p>'Make petrol cars more expensive to subsidise EVs': A report commissioned by the Department for Transport has urged the government to introduce of a 'feebate' scheme for electric cars. This would reduce the cost of plug-in vehicles by raising the price of new petrols and diesels</p>

<p>The report outlines the key areas for the Government to tackle the slow adoption to electric cars.</p>

<p>This includes raising awareness of EV benefits, improvements to the public charging infrastructure, changing consumer attitudes towards battery cars with limited ranges and consideration of financial factors to make plug-in models more attainable. </p>

<p>For the latter, the study produced by the Behavioural Insights Team and the Transport Research Laboratory has suggested higher VAT rates for petrol and diesel cars, or forcing buyers of these models to pay towards making electric cars cheaper.</p>

<p>This would see the cost of new cars with internal combustion engines likely increase by between £500 and £1,500. </p>

<p>The scheme, dubbed a 'feebate' system, would be one of the 'most cost-effective' ways to encourage a faster transition to EVs, the report said. </p>

<p>The study concluded that a such a scheme could be offered alongside the existing incentives, including the £3,000 Plug-in Car Grant and, from a government perspective, be easier to implement than VAT changes.</p>

<p>'A feebate would be a major policy announcement, but one which we feel has the potential for high impact if done right,' it said.</p>

<p>'By applying only to new cars it avoids being regressive, and is therefore one of the more promising incentive options.' </p>

<p>The study produced by the Behavioural Insights Team and the Transport Research Laboratory has suggested higher VAT rates for petrol and diesel cars or forcing buyers of these models to pay up to £1,500 towards making electric cars cheaper</p>

<p>Despite the recommendation, surveys and focus groups coordinated by the researchers found little public support for a electric-vehicle feebate scheme.</p>

<p>'Higher acceptance will likely depend on EVs being a truly viable alternative to all, so that the feebate does not end up punishing those who feel unable or unwilling to buy an EV - this requires policy to simultaneously address other technological and psychological barriers,' the report explained, </p>

<p>'One potential variation would be to (initially) apply a fee only to fleets, but the rebate across all EVs sold. </p>

<p>'It is also worth noting this idea was framed principally in terms of increasing the cost of an ICEV [internal combustion engine vehicles] within the survey, so we would expect a relatively negative response.'</p>

<p>Britain's motor industry's trade body has responded to the report with a hard stance in opposition of any scheme that punishes those who aren't yet happy to switch to a battery car.</p>

<p>Mike Hawes, chief executive at the Society of Motor Manufacturers and Traders, told This is Money: 'Manufacturers invested over £54billion last year alone to introduce more zero emission vehicles so we welcome appropriate initiatives that boost their popularity. </p>

<p>'Market transformation, however, will need world-class support including investment in charging infrastructure plus purchase incentives. These should include no tax on zero emission-capable cars, alongside a long-term commitment to the Plug-in Grant. </p>

<p>'We need positive measures, not those that penalise consumers who cannot yet afford the latest electric technology, do not have adequate charging facilities, or for whom driving requirements are not suited to electrification. </p>

<p>'To do otherwise could risk stalling fleet renewal and delaying environmental improvements by leaving them with no alternative but to keep their older vehicle for longer.'</p>

<p>Other recommendations made in the report includes new laws stipulating that all petrol stations must install electric car charge points and rebranding the government's marketing of electric car charging as 'free fuel'.</p>

<p>James Blackham, chief executive of insurance firm By Miles, said forcing drivers to pay £1,500 more for a petrol or diesel vehicle is 'not the answer to encourage uptake of greener transport options'. </p>

<p>He added: 'Obviously reducing the price of electric vehicles will help make this new technology more accessible, but it doesn’t make sense to hurt drivers that can’t necessarily afford these new vehicles.</p>

<p>'We must make it easier for motorists to make smarter driving choices that help the environment, but we can do this without pricing them out of owning a vehicle altogether.'</p>

<p>Transport minister, Grant Shapps, owns an electric Tesla Model 3. Yesterday, he opened the UK's largest EV charging hub at a rail station at Hatfield</p>

<p>Mr Shapps has propose for local authorities to paint parking spaces green in their busiest locations to reserved them exclusively for EVs as part of widening incentives for zero-emission cars</p>

<p>The paper's release coincided with World EV Day, which took place on Wednesday as part of a campaign to encourage more drivers to switch to plug-in vehicles.</p>

<p>Transport minister, Grant Shapps - who owns an electric Tesla Model 3 - used the event to open Hatfield train station's charging hub of 27 devices - the biggest of its kind at a UK rail station - and propose painting parking spaces green in some areas to show they are reserved for EVs.</p>

<p>The measures are park of the Government's desperation to  accelerate the take-up of electric cars, which in turn will cut air pollution levels.</p>

<p>The ambitious plans form part of a drive to achieve net-zero emissions by 2050, with Prime Minister Boris Johnson already committed to banning sales of new petrol, diesel and hybrid cars by 2035 - a deadline that could still be brought forward by five years.</p>

<p>It is also believed that Chancellor Rishi Sunak could end the 10-year freeze on fuel duty in his Autumn statement, increasing the tax of 57.95p per litre by as much as 5p' to pay nation's Covid-19 bill. </p>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('_layouts.post', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>