<?php $__env->startSection('content'); ?><p>Roma are said to finally be making a breakthrough in their attempts to permanently sign Chris Smalling from Manchester United.</p>

<p>The Italian giants have been working hard to secure a deal for the defender, despite the apparent reluctance of United to sell.</p>

<p>And now Roma have at least made some headway with a bid of £18million plus bonuses being prepared to be sent over to Old Trafford, according to Sky Sports Italia.</p>

<p>Roma are working on an improved deal to seal the permanent signing of Chris Smalling</p>

<p>Following a loan switch to Serie A Smalling gained critical acclaim, following an impressive rise in form in his 37 games, which included three goals.</p>

<p>United were understood to be holding out for a fee of £20m for the 30-year-old, but are tipped to do business depending on the quality of Roma's added bonuses in the deal.</p>

<p>Smalling's United days look to be over after impressing during his loan spell in Serie A</p>

<p>Ole Gunnar Solskjaer would use funds generated by Smalling's sale to continue overhauling</p>

<p>United boss Ole Gunnar Solskjaer is looking to bolster his defensive line this summer if possible, in order to tighten the ranks ahead of next season.</p>

<p>RB Leipzig star Dayot Upamecano has already been linked with a move to Old Trafford, though Arsenal and Manchester City are also said to hold an interest in the 21-year-old.</p>

<p>The youngster has a £38m release clause in his new deal at Leipzig but it cannot be triggered until next summer, meaning United would be forced to pay a hefty sum to lure him away. </p>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('_layouts.post', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>