<?php $__env->startSection('content'); ?><p>Astronomers have detected a monster black hole 150 times heavier than our Sun as a result of the energy wave produced when two smaller black holes merged. </p>

<p>Researchers using the LIGO and Virgo gravitational wave detectors spotted a wave with eight times the energy of the Sun coming from 17 billion light years away.</p>

<p>This energetic gravitational wave was the result of a black hole 66 times the size of the Sun merging with a larger black hole about 85 times the mass of the Sun.  </p>

<p>The new black hole is twice as heavy as any previously observed using gravitational waves, according to researchers involved in the study from Monash University.  </p>

<p>Exactly how the two smaller waves came together is still unknown, but researchers think they both might be the result of multiple previous, smaller, black hole mergers. </p>

<p>Artist concept illustrating a hierarchical scheme for merging black holes. LIGO and Virgo recently observed a black hole merger with a final mass of 142 times that of the sun, making it the largest of its kind observed in gravitational waves to date</p>

<p>The signal, detected on May 21, has been labelled GW190521 - it takes months for the source to be confirmed as a gravitational wave and involves multiple researchers.</p>

<p>It resembles about four short wiggles and is extremely brief in duration, according to MIT astronomers -  lasting less than one-tenth of a second. </p>

<p>From what the researchers can tell, GW190521 was generated by a source that existed when the universe was about half its current age - making it one of the most distant gravitational-wave sources detected so far. </p>

<p>Scientists from the University of Glasgow assisted with the data analysis process that was required before it could be confirmed as a black hole merger.</p>

<p>The black holes have large and nearly equal masses, with one only 3 per cent more massive than the other</p>

<p>Daniel Williams, from the Physics and Astronomy Department, said: 'Gravitational wave astronomy continues to help us answer questions about how our universe works, as well as present us with exciting new problems to solve.</p>

<p>While astronomers believe the gravitational wave they detected was caused by a black hole merger, there are other possible explanations. </p>

<p>What if something entirely new produced these gravitational waves? </p>

<p>It's a tantalizing prospect, and in their paper the scientists briefly consider other sources in the universe that might have produced the signal they detected. </p>

<p>For instance, perhaps the gravitational waves were emitted by a collapsing star in our galaxy. </p>

<p>The signal could also be from a cosmic string produced just after the universe inflated in its earliest moments.</p>

<p>Neither of these exotic possibilities matches the data as well as a binary merger - so they went with that.</p>

<p>"Since we first turned on LIGO, everything we've observed with confidence has been a collision of black holes or neutron stars," the team explained. </p>

<p>"This is the one event where our analysis allows the possibility that this event is not such a collision.'</p>

<p>Although this event is consistent with being from an exceptionally massive binary black hole merger, other options are possible, they said.</p>

<p>'Because we have all been hoping for something new, something unexpected, that could challenge what we've learned already. This event has the potential for doing that."</p>

<p>Researchers will continue to comb through the data to see if other explanations 'could' be a better fit, but for now a black hole merger is the most likely cause.</p>

<p>'This detection gives us a fascinating first look at the physics of intermediate-mass black holes, and opens up the opportunity for future detections to solve the mystery of just how they are formed.'</p>

<p>Given the size of the black holes before they merged, astronomers believe the smaller black holes could have already been the products of previous mergers.</p>

<p>OzGrav postdoctoral researcher Simon Stevenson, from Swinburne University of Technology, says the two 'impossibly' massive black holes that led to the monster black hole could have been the result of multiple mergers.</p>

<p>'If true, we have a big black hole made of smaller black holes, with even smaller black holes inside them—like Russian Dolls.'</p>

<p>This type of hierarchical combining of black holes has been hypothesised in the past but, if proved correct, this would be the first evidence for such activity.</p>

<p>In this latest discovery we are witnessing the birth of an intermediate mass black hole, researchers explained.</p>

<p>That is a black hole more than 100 times as heavy as the Sun, almost twice as heavy as any black hole previously observed with gravitational-waves. </p>

<p>These intermediate mass black holes could be the seeds that grow into the supermassive black holes that reside in the centres of galaxies. </p>

<p>The scientists identified the merging black holes by detecting the gravitational waves - ripples in the fabric of space-time - produced in the merger's final moments.</p>

<p>The gravitational waves from GW190521 were detected on May 21, 2019, by the twin LIGO detectors located in Livingston, Louisiana, and Hanford, Washington, and the Virgo detector located near Pisa, Italy.</p>

<p>'The mass of the larger black hole in the pair puts it into the range where it's unexpected from regular astrophysics processes,' said Peter Shawhan, a professor of physics at UMD.</p>

<p>'It seems too massive to have been formed from a collapsed star, which is where black holes generally come from.' </p>

<p>According to current understanding, stars that could give birth to black holes with masses between 65 and 135 times greater than the sun don't collapse on death.</p>

<p>Therefore, astronomers don't expect them to form black holes.</p>

<p>'Right from the beginning, this signal, which is only a tenth of a second long, challenged us in identifying its origin,' said UMD Professor Alessandra Buonanno.</p>

<p>'Despite its short duration, we were able to match the signal to one expected of black-hole mergers, as predicted by Einstein's theory of general relativity,' she said.</p>

<p>'We realized we had witnessed, for the first time, the birth of an intermediate-mass black hole from a black-hole parent that most probably was born from an earlier binary merger.'</p>

<p>Numerical simulation of two black holes that inspiral and merge, emitting gravitational waves. Researchers using the LIGO and Virgo gravitational wave detectors spotted a wave with eight times the energy of the Sun coming from 17 billion light years away</p>

<p>GW190521 is one of three recent gravitational wave discoveries that challenge current understanding of black holes and allow scientists to test Einstein's theory of general relativity in new ways. </p>

<p>As LIGO and Virgo detectors listen for gravitational waves passing through Earth, automated searches comb through the incoming data for interesting signals. </p>

<p>These searches can use two different methods: </p>

<p>LIGO member Salvatore Vitale, assistant professor of physics at MIT, likens compact binary searches to 'passing a comb through data, that will catch things in a certain spacing,' in contrast to burst searches that are more of a 'catch-all' approach.</p>

<p>In the case of GW190521, it was a burst search that picked up the signal slightly more clearly, opening the very small chance that the gravitational waves arose from something other than a binary merger.</p>

<p>'The bar for asserting we've discovered something new is very high,' Weinstein says. </p>

<p>'So we typically apply Occam's razor: The simpler solution is the better one, which in this case is a binary black hole.' </p>

<p>The other two events included the first observed merger of two black holes with distinctly unequal masses and a merger between a black hole and a mystery object, which may be the smallest black hole or the largest neutron star ever observed.  </p>

<p>'All three events are novel with masses or mass ratios that we've never seen before,' said Shawhan</p>

<p>'So not only are we learning more about black holes in general, but because of these new properties, we are able to see effects of gravity around these compact bodies that we haven't seen before.' </p>

<p>For example, the theory of general relativity predicts that binary systems with distinctly unequal masses will produce gravitational waves with higher harmonics, and that is exactly what the scientists were able to observe for the first time. </p>

<p>OzGrav Chief Investigator and co-author David Ottaway, from University of Adelaide, says this is a huge step towards understand the link between the smaller black holes that have been seen by gravitational-wave detectors and the massive black holes that are found in the centre of galaxies. </p>

<p>Professor Sheila Rowan, director of the University of Glasgow's Institute for Gravitational Research, said upgrading equipment on the detectors is vital.  </p>

<p>'It translates into more detections, an improved rate of detections, and also detections of individual events made at higher sensitivities. </p>

<p>'That enables detections like this one, where the very low frequency of the signal might well have been impossible to pick out of the background noise without our improvements.' </p>

<p>In addition to these three black hole mergers and a previously reported binary neutron star merger, the observational run from April 2019 through March 2020 identified 52 other potential gravitational wave events. </p>

<p>'Gravitational wave events are being detected regularly,' Shawhan said, 'and some of them are turning out to have remarkable properties which are extending what we can learn about astrophysics.' </p>

<p>Details of the discovery have been published in the journals Physical Review Letters and Astrophysical Journal Letters.  </p>

<p>Ligo is made up of two observatories that detect gravitational waves by splitting a laser beam and sending it down several mile (kilometre) long tunnels before merging the light waves together again.</p>

<p>A passing gravitational wave changes the shape of space by a tiny amount, and the Ligo was built with the ability to measure a change in distance just one-ten-thousandth the width of a proton.</p>

<p>However, this sensitivity means any amount of noise, even people running at the site, or raindrops, can be detected. </p>

<p>The Ligo detectors are interferometers that shine a laser through a vacuum down two arms in the shape of an L that are each 2.5 miles (four kilometres) in length.</p>

<p>The light from the laser bounces back and forth between mirrors on each end of the L, and scientists measure the length of both arms using the light.</p>

<p>If there's a disturbance in space-time, such as a gravitational wave, the time the light takes to travel the distance will be slightly different in each arm making one arm look longer than the other.</p>

<p>Ligo (pictured) is made up of two observatories that detect gravitational waves by splitting a laser beam and sending it down several mile (kilometre) long tunnels before merging the light waves together again</p>

<p>Ligo scientists measure the interference in the two beams of light when they come back to meet, which reveals information on the space-time disturbance.</p>

<p>The ensure the results are accurate, Ligo uses two observatories, 1,870 miles (3,000 kilometres) apart, which operate synchronously, each double-checking the other's observations.</p>

<p>The noise at each detector should be completely uncorrelated, meaning a noise like a storm nearby one detector doesn't show up as noise in the other.</p>

<p>Some of the sources of 'noise' the team say they contend with include: 'a constant 'hiss' from photons arriving like raindrops at our light detectors; rumbles from seismic noise like earthquakes and the oceans pounding on the Earth's crust; strong winds shaking the buildings enough to affect our detectors.'</p>

<p>However, if a gravitational wave is found, it should create a similar signal in both instruments nearly simultaneously. </p>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('_layouts.post', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>