<?php $__env->startSection('content'); ?><p>Scientists have created a miniature 'wind turbine' that 'scavenges' energy from a breeze created during a brisk walk. </p>

<p>The 'nano-generator', which is made of two plastic strips in a tube, captures and stores wind energy to power electronic devices. </p>

<p>It's inspired by giant wind turbines that convert the kinetic energy of wind into power, but it shrinks the concept down to something that could be worn around the wrist. </p>

<p>The nano-generator has already been used to power LED light and in the future could charge electronic gadgets on the go, including smartphones.   </p>

<p>Scroll down for video </p>

<p>Currently, the research team's device can power up 100 LED lights and temperature sensors</p>

<p>The Chinese engineers behind the device think the abundance and cost-effectiveness of wind should be made use of by new smaller devices. </p>

<p>Currently, the device can power up 100 LED lights and temperature sensors. </p>

<p>'You can collect all the breeze in your everyday life,' said study author Ya Yang of Beijing Institute of Nanoenergy and Nanosystems, Chinese Academy of Sciences. </p>

<p>'We once placed our nano-generator on a person's arm, and a swinging arm's airflow was enough to generate power.' </p>

<p>High costs, resulting noise ad 'aesthetic pollution' are still issues of the fulls-scale wind turbines that offer a carbon-free source of energy. </p>

<p>Most of the wind available on land is also too gentle to push commercial wind turbine blades, which is why many are stationed out at sea. </p>

<p>Now the researchers have found a way to scavenge less powerful gusts.  </p>

<p>The new device is not technically a turbine but a 'nano-generator' made of two plastic strips in a tube, which flutter or clap together when there is airflow. </p>

<p>The two plastics become electrically charged after being separated from each other as they're flapping. </p>

<p>The 'nano-generator', which is made of two plastic strips in a tube, captures and stores wind energy to power electronic devices</p>

<p>Illustration shows how the two bits of ribbon come into contact - which captures and stores energy. The green fluorescent bulbs in the picture were used to identify the trajectory of two flapping film</p>

<p>This phenomenon is called the 'triboelectric effect' and explains why our hair becomes electrically charged after being rubbed with a balloon.</p>

<p>But instead of making hair stand up, the electricity generated by the two plastic strips is captured and stored. </p>

<p>In tests, a breeze as gentle as 3.6 miles per hour was enough to power the nano-generator. </p>

<p>But it performs best when wind velocity is between 8.9 to 17.9 miles per hour – a speed that allows the two plastic strips to flutter in sync. </p>

<p>The device also has a high wind-to-energy conversion efficiency of 3.23 per cent, a value that exceeds previously reported performances on wind energy scavenging. </p>

<p>Wind efficiency – the amount of kinetic energy in the wind that is converted to mechanical energy and electricity – is around 35 to 45 per cent for full-scale turbines.  </p>

<p>The practicality of the nano-generator in an outdoor environment. The outdoor breeze is enough to flutter the plastic strips, shown in red</p>

<p>'Our intention isn't to replace existing wind power generation technology – it's to solve the issues that the traditional wind turbines can't solve,' said Yang. </p>

<p>'Unlike wind turbines that use coils and magnets, where the costs are fixed, we can pick and choose low-cost materials for our device. </p>

<p>'Our device can also be safely applied to nature reserves or cities because it doesn't have the rotating structures.'</p>

<p>In the future, Yang and colleagues would like to combine the device to small electronic devices such as phones, to provide sustainable electric power.</p>

<p>They also want to scale-up the device to make it bigger and more powerful. </p>

<p>'I'm hoping to scale up the device to produce 1,000 watts, so it's competitive with traditional wind turbines,' said Yang. </p>

<p>'We can place these devices where traditional wind turbines can't reach, we can put it in the mountains or on the top of buildings for sustainable energy.'         </p>

<p>The system has been detailed in Cell Reports Physical Science. </p>

<p>Wind turbines operate on a simple principle- the energy in the wind turns propeller-like blades around a rotor.</p>

<p>The rotor is connected to the main shaft, which spins a generator to create electricity.  </p>

<p>They work in the opposite way to a fan, instead of using electricity to make wind, like a fan, wind turbines use wind to make electricity.</p>

<p>There are two main types of wind turbine that operate on the same basic principle. </p>

<p>Off-shore ones are larger and tend to create more energy and are often built in large groups, known as wind farms. </p>

<p>These provide bulk power to the National Grid.  </p>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('_layouts.post', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>