<?php $__env->startSection('content'); ?><p>Saracens are out of their European bubble and staring into the abyss. The glorious diversion of a Champions Cup campaign has given way to an uncertain future, at least in the short term.</p>

<p>Saturday’s agonising defeat by Racing 92 has forced Mark McCall and his squad to accept the uncomfortable reality of their looming fall from grace. But where to now for the club collectively and so many of its high-profile players individually?</p>

<p>In theory, a week from now they will be destined for the Championship, but there is no knowing when the country’s second division will launch its 2020-21 season.</p>

<p>Saracens must now face their impending fall from the Premiership after a Champions Cup exit</p>

<p>Given the warnings that empty grounds make the under-funded league unviable — and the possibility crowds won’t be allowed until April — there may not be a proper campaign at all, which threatens a rapid Saracens return to the Premiership.</p>

<p>A core of senior England players have committed to stay but short-term loans may now be considered, if there is an empty fixture list next spring. </p>

<p>Owen Farrell, Maro Itoje, Billy and Mako Vunipola, Jamie George and Elliot Daly will be in Test mode this autumn and for the Six Nations but after that they will need game-time before the Lions tour of South Africa.</p>

<p>Juan Imhoff's late try ensured that Saracens now have to focus on what comes next </p>

<p>After next season, Ben Earl, Max Malins, Nick Isiekwe, Alex Goode and Jack Singleton are all due to return from loans elsewhere, but will that happen if Saracens haven’t bounced back?</p>

<p>Others such as Manu Vunipola, Rotimi Segun, Sam Crean and Dom Morris have also emerged as proof that the club’s academy remains a formidable talent production line. But they will need to know that they can compete in the Premiership to advance their careers.</p>

<p>As George admitted: ‘The element of the unknown is horrendous. God knows what we are going to be facing but we are used to being thrown curveballs.’</p>

<p>There may yet be an alternative. There are now grave concerns that one or more of the elite clubs will go out of business, within months. Worcester are thought to be especially vulnerable and their owners have spoken frankly about facing a ‘fight for survival’.</p>

<p>High-profile stars such as Owen Farrell will now be wondering what is next for the club </p>

<p>If the Premiership dozen become 11 because one club is unable to stay afloat, the latest indications are that the rest would do whatever is necessary to keep the show on the road. </p>

<p>That could mean offering Saracens a reprieve by keeping them in the league rather than banishing them for past salary cap offences. Principles would be trumped by pragmatism.</p>

<p>Saracens could find themselves in limbo in the new year, or still in the Premiership. They could be loaning out more players, or needing to strengthen again in a hurry.</p>

<p>The golden era is over and nobody knows yet what the next phase will look like. McCall’s squad are bound to be in title-chasing mode again at some stage — but when is anyone’s guess.</p>

<p>The weekend’s European results may have profound implications in the tussle for Premiership play-off places going into a busy final week of regular-season fixtures.</p>

<p>Saracens’ defeat could prove to be very bad news for Bath, who face the outgoing champions at Allianz Park on Sunday.</p>

<p>Mark McCall is far more likely to name a line-up full of highly motivated leading men than would have been the case if Saracens were keeping their powder dry for a Champions Cup final.</p>

<p>Wasps can keep themselves in the title hunt if they win at Harlequins tonight, but they are up against a home side with their own powerful agenda — to give captain Chris Robshaw a memorable send-off.</p>

<p>Saracens' defeat could harm Bath when the sides meet in a crucial Premiership clash</p>

<p>There was wild rejoicing in rugby circles on Saturday when Welsh referee Nigel Owens took a stand against the scourge of so-called ‘caterpillar’ rucks, which lead to so much tedious time-wasting. </p>

<p>With 20 minutes, 28 seconds on the clock in Paris, Owens told Racing to ‘use it’, which means they had five seconds to comply. They did not, so at 20.36 he blew the whistle and awarded Saracens a scrum. </p>

<p>His decisive action and subsequent warnings worked, as neither side dawdled at the base of rucks from then on. More of this please. </p>

<p>Nigel Owens earned praise from rugby fans on Saturday night for his refereeing of Racing 92</p>

<p>It is exactly four years since then RFU chief executive Ian Ritchie dismissed requests by southern hemisphere nations for a greater share of vast profits generated by Tests at Twickenham. </p>

<p>His words echoed last week when the RFU pleaded for a Government bailout.</p>

<p>While Covid-19 is creating a gaping hole in sporting bank accounts globally, it is fair to wonder what became of the English windfall from staging the 2015 World Cup. </p>

<p>The RFU won't be getting any sympathy from rival nations as they struggle amid the pandemic</p>

<p>A major overspend on the Twickenham East Stand redevelopment — designed to corner the lucrative Test hospitality market — contributed to heavy job cuts in 2018 and a situation now where there is not enough of a financial safety net.</p>

<p>Rival countries often felt that the RFU didn’t wear their wealth lightly, or show enough consideration for the game’s have-nots.</p>

<p>They won’t be shedding too many tears now.</p>

<p>Best finish</p>

<p>Bordeaux’s rookie France fly-half Matthieu Jalibert showed deft footwork as he took a pass from Cameron Woki and danced past Max Malins to score at Bristol.</p>

<p>Young Bordeaux fly-half Matthieu Jalibert impressed against Bristol at the weekend </p>

<p>Pure genius</p>

<p>Finn Russell had been shackled by Saracens, but the Scottish playmaker pulled a rabbit out of a hat with the trademark chip to create Racing’s match-winning try.</p>

<p>Pass master</p>

<p>Exeter’s triumph against Toulouse was founded on more than just forward muscle, as Ollie Devoto proved when his classy cut-out to Tom O’Flaherty wide on the left ignited a Chiefs attack.</p>

<p>Ollie Devoto was this week's pass master after his cut-out during Exeter's clash with Toulouse</p>

<p>Surface issues</p>

<p>Toulon spend a lot of money on their team but evidently not on the pitch at Stade Mayol, which was in a bad state for Leicester’s visit.</p>

<p>Fitting finals</p>

<p>Exeter-Racing and Bristol-Toulon are proper continental deciders which promise fascinating culture clashes. Mixed-nationality showpieces are better for the health of these events.</p>
<?php $__env->stopSection(); ?>
<?php echo $__env->make('_layouts.post', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?>