name: "Post Links"
on:
    schedule:
        - cron: "*/30 * * * *"
jobs:
    post-links:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: "Install Composer Dependencies"
                run: "composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist"
            -   name: "Run Link Poster"
                run: "php ./tools/twitter/Find.php $TWITTER_API_KEY $TWITTER_API_SECRET $TWITTER_ACCESS_TOKEN $TWITTER_ACCESS_TOKEN_SECRET"
                env:
                  TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
                  TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
                  TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
                  TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
